[package]
name = "dk"
version = "0.1.0"
edition = "2024"

[dependencies]
colored = "2.0"
prettytable-rs = "0.10.0"
regex = "1.11.1"
serde_json = "1.0.140"
serde = { version = "1.0.219", features = ["derive"] }
dirs = "6.0.0"
rustc_version = "0.4.1"
